### ISSUE TITLE
Behaviour when in-memory buffer exceeds limit

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-logger-ruby#32]
Hi

https://github.com/fluent/fluent-logger-ruby/blob/master/lib/fluent/logger/fluent_logger.rb#L169

If my td-agent process dies, then I can see that the behaviour is to write any messages into a buffer (`@pending`). When this buffer exceeds the max size limit then the buffer is flushed. This results in data loss.

Is there a way to configure this behaviour so that for example instead of simply throwing away those messages I can write to disk? Simply increasing the size limit of the buffer makes the issue less severe, but it's not really feasible if my servers don't have a lot of RAM. Flushing to disk would be especially useful if my EC2 instances are setup with EFS so that I would never lose any events.

I _could_ monkey-patch this in my app but I'm wondering if there is a more elegant solution to this problem.

Thanks.

**Comment by edjames** [comment]
Thinking a little more on this, I think it would be quite simple to allow my own object to be injected via config, which could then handle this scenario. So as long as that object implements a specific interface then this could be quite simple.

I will test and submit a pull request.

Any other suggestions would be most welcome.

**Comment by edjames** [comment]
Pull request here: https://github.com/fluent/fluent-logger-ruby/pull/33

**Comment by repeatedly** [comment]
Already merged
