### ISSUE TITLE
Anyone reading this?

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-logger-ruby#34]
Hello

There are a few pull requests (one is mine) which have not yet been merged. 2 of them seem very old so I'm wondering if anyone is actively maintaining this repo.

I don't want to step on anyone's toes or anything, just wondering.

Thanks.

**Comment by kiyoto** [comment]
Heya-

Most definitely. We (Treasure Data) use this in production, so rest assured, this project is actively maintained.

@repeatedly might be the best person to look at your PR.

**Comment by edjames** [comment]
Great, thanks very much.
